services:
  duotasker:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8887:80"
      - "8888:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.template:/etc/nginx/templates/default.conf.template
      - static_volume:/app/staticfiles
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - duotasker
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

volumes:
  static_volume:

networks:
  app-network:
    driver: bridge
