version: '3'
services:
  DuoTasker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8888:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.template:/etc/nginx/templates/default.conf.template
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - web
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
