services:
  duotasker:
    image: beetwenty/duotasker:latest
    volumes:
      - /path/to/static/:/app/staticfiles/
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /path/to/nginx.conf:/etc/nginx/nginx.conf
      - /path/to/static:/app/staticfiles/
    environment:
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - duotasker
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

volumes:
  static_volume:

networks:
  app-network:
    driver: bridge
