# Generated by Django 5.0 on 2024-02-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='catergory',
            new_name='category',
        ),
    ]
