# Generated by Django 5.0 on 2024-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_catergory_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-is_important', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
