# Generated by Django 5.0 on 2024-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_category_options_category_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated list of keywords to match for this category', null=True),
        ),
    ]
