# Generated by Django 5.0 on 2024-02-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_uncategorized',
            field=models.BooleanField(default=False, help_text="Mark as the special 'Uncategorized' category"),
        ),
    ]
