# Generated by Django 5.0 on 2024-02-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_task_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
    ]
