# Generated by Django 5.0 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_task_completed_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_important', 'name'], name='base_catego_is_impo_4f5739_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_uncategorized'], name='base_catego_is_unca_8f7fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed'], name='base_task_completed_6886aa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='base_task_category_9c5c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='base_task_title_6f0c74_idx'),
        ),
    ]
