# Generated by Django 5.0 on 2026-04-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_add_query_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('default_timezone', models.CharField(default='UTC', max_length=64)),
                ('setup_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
